name: Deploy Astro Site to Pages

on:
  push:
    branches: [ main ] # Change to master if your default branch is master

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  ASTRO_TELEMETRY_DISABLED: 1

jobs:
  build:
    name: Build Astro
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v6

      - name: Install, cache, and build site
        uses: withastro/action@v6
        # If your Astro site isn't in the root of your repo,
        # specify it here: with: { path: "./subfolder" }

  deploy:
    needs: build
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
